spring:
  application:
    name: transaction-service

  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
